// Copyright (C) 2026 CVAT.ai Corporation
//
// SPDX-License-Identifier: MIT

import { QCErrorType, QCSessionSummary, SceneQCResult } from './qc-types';

export const MOCK_QC_DATA: QCSessionSummary = {
    datasetName: 'nuScenes-v1.0-mini-annotated.zip',
    fileSizeMb: 412.5,
    uploadedAt: '2026-10-09 20:45:10',
    backendTaskStatus: 'Completed (Analyzed 6 scenes, 240 frames)',
    cvatTaskId: 42,
    cvatTaskName: 'nuScenes_v1.0_3D_QC_Inspection_Task_42',
    totalScenes: 6,
    totalFrames: 240,
    totalCuboids: 1420,
    totalIssues: 49,
    errorCounts: {
        [QCErrorType.FEW_LIDAR_POINTS]: 19,
        [QCErrorType.IRRATIONAL_SIZE]: 12,
        [QCErrorType.OVERLAPPING_CUBOIDS]: 9,
        [QCErrorType.OPPOSITE_HEADING]: 9,
    },
    scenes: [
        {
            id: 'scene_001',
            token: 'fcbccedd61424f1b85dcbf8f897f0223',
            sceneName: 'scene-0061 (Boston Seaport - Drizzle)',
            location: 'Boston - Seaport Blvd & Congress St',
            description: 'Trời mưa nhỏ, chập tối, lưu lượng xe cộ đông đúc gần giao lộ cảng',
            taskId: 42,
            jobId: 101,
            frameCount: 40,
            totalCuboids: 260,
            errorCounts: {
                [QCErrorType.FEW_LIDAR_POINTS]: 7,
                [QCErrorType.IRRATIONAL_SIZE]: 3,
                [QCErrorType.OVERLAPPING_CUBOIDS]: 2,
                [QCErrorType.OPPOSITE_HEADING]: 2,
                total: 14,
            },
            riskLevel: 'high',
            suspectedCuboids: [
                {
                    id: 'cub_61_01',
                    trackId: 'trk_car_104',
                    frame: 14,
                    timestamp: '00:07.000',
                    label: 'car',
                    errorType: QCErrorType.FEW_LIDAR_POINTS,
                    severity: 'critical',
                    reason: 'Chỉ có 2 điểm phản xạ LiDAR bên trong bounding box (ngưỡng tối thiểu: 5 điểm)',
                    metrics: {
                        pointCount: 2,
                        minPointThreshold: 5,
                    },
                    cvatUrl: '/tasks/42/jobs/101?frame=14&focus=trk_car_104',
                    status: 'pending',
                },
                {
                    id: 'cub_61_02',
                    trackId: 'trk_car_104',
                    frame: 15,
                    timestamp: '00:07.500',
                    label: 'car',
                    errorType: QCErrorType.FEW_LIDAR_POINTS,
                    severity: 'critical',
                    reason: 'Chỉ có 1 điểm phản xạ LiDAR bên trong bounding box, nghi ngờ bị che khuất hoặc gán nhãn ảo',
                    metrics: {
                        pointCount: 1,
                        minPointThreshold: 5,
                    },
                    cvatUrl: '/tasks/42/jobs/101?frame=15&focus=trk_car_104',
                    status: 'pending',
                },
                {
                    id: 'cub_61_03',
                    trackId: 'trk_truck_118',
                    frame: 22,
                    timestamp: '00:11.000',
                    label: 'truck',
                    errorType: QCErrorType.IRRATIONAL_SIZE,
                    severity: 'critical',
                    reason: 'Chiều dài 14.8m x Rộng 3.8m x Cao 4.7m vượt 45% chuẩn kích thước xe tải thông dụng',
                    metrics: {
                        dimensions: { length: 14.8, width: 3.8, height: 4.7 },
                        expectedDimensionsRange: 'Dài: 6.0-11.5m, Rộng: 2.2-2.9m, Cao: 2.5-3.8m',
                    },
                    cvatUrl: '/tasks/42/jobs/101?frame=22&focus=trk_truck_118',
                    status: 'pending',
                },
                {
                    id: 'cub_61_04',
                    trackId: 'trk_car_145',
                    frame: 28,
                    timestamp: '00:14.000',
                    label: 'car',
                    errorType: QCErrorType.OVERLAPPING_CUBOIDS,
                    severity: 'critical',
                    reason: 'Giao thoa không gian 3D (IoU = 0.34) với cuboid trk_car_146 tại cùng thời điểm',
                    metrics: {
                        overlapIou: 0.34,
                        conflictingTrackId: 'trk_car_146',
                    },
                    cvatUrl: '/tasks/42/jobs/101?frame=28&focus=trk_car_145',
                    status: 'pending',
                },
                {
                    id: 'cub_61_05',
                    trackId: 'trk_bus_162',
                    frame: 31,
                    timestamp: '00:15.500',
                    label: 'bus',
                    errorType: QCErrorType.OPPOSITE_HEADING,
                    severity: 'warning',
                    reason: 'Góc yaw (175°) lệch 162° so với hướng vector vận tốc di chuyển (xe đang tiến về trước nhưng cuboid quay lùi)',
                    metrics: {
                        yawAngleDeg: 175.4,
                        motionVectorDeg: 13.2,
                        angleDeltaDeg: 162.2,
                    },
                    cvatUrl: '/tasks/42/jobs/101?frame=31&focus=trk_bus_162',
                    status: 'pending',
                },
                {
                    id: 'cub_61_06',
                    trackId: 'trk_ped_190',
                    frame: 8,
                    timestamp: '00:04.000',
                    label: 'pedestrian',
                    errorType: QCErrorType.FEW_LIDAR_POINTS,
                    severity: 'warning',
                    reason: 'Chỉ có 3 điểm LiDAR, nằm sát mép chùm tia cảm biến',
                    metrics: {
                        pointCount: 3,
                        minPointThreshold: 5,
                    },
                    cvatUrl: '/tasks/42/jobs/101?frame=8&focus=trk_ped_190',
                    status: 'pending',
                },
                {
                    id: 'cub_61_07',
                    trackId: 'trk_ped_190',
                    frame: 9,
                    timestamp: '00:04.500',
                    label: 'pedestrian',
                    errorType: QCErrorType.FEW_LIDAR_POINTS,
                    severity: 'warning',
                    reason: 'Chỉ có 2 điểm LiDAR, đối tượng cách xe tự hành >45 mét',
                    metrics: {
                        pointCount: 2,
                        minPointThreshold: 5,
                    },
                    cvatUrl: '/tasks/42/jobs/101?frame=9&focus=trk_ped_190',
                    status: 'pending',
                },
                {
                    id: 'cub_61_08',
                    trackId: 'trk_car_201',
                    frame: 18,
                    timestamp: '00:09.000',
                    label: 'car',
                    errorType: QCErrorType.IRRATIONAL_SIZE,
                    severity: 'warning',
                    reason: 'Chiều cao cuboid 2.6m vượt quá chiều cao xe sedan tiêu chuẩn',
                    metrics: {
                        dimensions: { length: 4.8, width: 2.0, height: 2.6 },
                        expectedDimensionsRange: 'Cao chuẩn sedan: 1.4-1.8m',
                    },
                    cvatUrl: '/tasks/42/jobs/101?frame=18&focus=trk_car_201',
                    status: 'pending',
                },
            ],
        },
        {
            id: 'scene_002',
            token: '32530f032259469e926f62c6d3fa71b4',
            sceneName: 'scene-0103 (Singapore - One North Intersection)',
            location: 'Singapore - Fusionopolis Way & Ayer Rajah Cres',
            description: 'Giao lộ đông đúc giờ cao điểm, nhiều xe bus và xe máy rẽ trái đồng thời',
            taskId: 42,
            jobId: 102,
            frameCount: 40,
            totalCuboids: 340,
            errorCounts: {
                [QCErrorType.FEW_LIDAR_POINTS]: 4,
                [QCErrorType.IRRATIONAL_SIZE]: 4,
                [QCErrorType.OVERLAPPING_CUBOIDS]: 4,
                [QCErrorType.OPPOSITE_HEADING]: 3,
                total: 15,
            },
            riskLevel: 'high',
            suspectedCuboids: [
                {
                    id: 'cub_103_01',
                    trackId: 'trk_motorcycle_042',
                    frame: 6,
                    timestamp: '00:03.000',
                    label: 'motorcycle',
                    errorType: QCErrorType.OVERLAPPING_CUBOIDS,
                    severity: 'critical',
                    reason: 'Cuboid xe máy va chạm/chồng chéo IoU 0.28 với trk_pedestrian_088 đang qua đường',
                    metrics: {
                        overlapIou: 0.28,
                        conflictingTrackId: 'trk_pedestrian_088',
                    },
                    cvatUrl: '/tasks/42/jobs/102?frame=6&focus=trk_motorcycle_042',
                    status: 'pending',
                },
                {
                    id: 'cub_103_02',
                    trackId: 'trk_bus_055',
                    frame: 12,
                    timestamp: '00:06.000',
                    label: 'bus',
                    errorType: QCErrorType.OPPOSITE_HEADING,
                    severity: 'critical',
                    reason: 'Xe bus đang chuyển làn nhưng cuboid yaw angle bị ngược chiều 180°',
                    metrics: {
                        yawAngleDeg: -88.5,
                        motionVectorDeg: 92.1,
                        angleDeltaDeg: 179.4,
                    },
                    cvatUrl: '/tasks/42/jobs/102?frame=12&focus=trk_bus_055',
                    status: 'pending',
                },
                {
                    id: 'cub_103_03',
                    trackId: 'trk_car_071',
                    frame: 19,
                    timestamp: '00:09.500',
                    label: 'car',
                    errorType: QCErrorType.IRRATIONAL_SIZE,
                    severity: 'critical',
                    reason: 'Kích thước cuboid quá nhỏ (Dài 2.1m, Rộng 1.1m) so với nhãn car',
                    metrics: {
                        dimensions: { length: 2.1, width: 1.1, height: 1.4 },
                        expectedDimensionsRange: 'Dài tối thiểu: 3.8m, Rộng: 1.7m',
                    },
                    cvatUrl: '/tasks/42/jobs/102?frame=19&focus=trk_car_071',
                    status: 'pending',
                },
                {
                    id: 'cub_103_04',
                    trackId: 'trk_car_094',
                    frame: 25,
                    timestamp: '00:12.500',
                    label: 'car',
                    errorType: QCErrorType.FEW_LIDAR_POINTS,
                    severity: 'warning',
                    reason: 'Chỉ có 3 điểm phản xạ LiDAR do vật thể bị phản chiếu trên bề mặt kính tòa nhà',
                    metrics: {
                        pointCount: 3,
                        minPointThreshold: 5,
                    },
                    cvatUrl: '/tasks/42/jobs/102?frame=25&focus=trk_car_094',
                    status: 'pending',
                },
            ],
        },
        {
            id: 'scene_003',
            token: 'cb8d234676be46ba8b982bb1663f7895',
            sceneName: 'scene-0553 (Boston Financial District - Construction Zone)',
            location: 'Boston - State St & Congress St',
            description: 'Khu vực công trường rào chắn, nhiều biển báo công trình và xe cẩu đỗ tĩnh',
            taskId: 42,
            jobId: 103,
            frameCount: 40,
            totalCuboids: 215,
            errorCounts: {
                [QCErrorType.FEW_LIDAR_POINTS]: 5,
                [QCErrorType.IRRATIONAL_SIZE]: 2,
                [QCErrorType.OVERLAPPING_CUBOIDS]: 1,
                [QCErrorType.OPPOSITE_HEADING]: 1,
                total: 9,
            },
            riskLevel: 'medium',
            suspectedCuboids: [
                {
                    id: 'cub_553_01',
                    trackId: 'trk_barrier_014',
                    frame: 4,
                    timestamp: '00:02.000',
                    label: 'truck',
                    errorType: QCErrorType.FEW_LIDAR_POINTS,
                    severity: 'critical',
                    reason: 'Chỉ có 1 điểm LiDAR phản xạ, bị che khuất bởi hàng rào tôn công trường',
                    metrics: {
                        pointCount: 1,
                        minPointThreshold: 5,
                    },
                    cvatUrl: '/tasks/42/jobs/103?frame=4&focus=trk_barrier_014',
                    status: 'pending',
                },
                {
                    id: 'cub_553_02',
                    trackId: 'trk_trailer_032',
                    frame: 15,
                    timestamp: '00:07.500',
                    label: 'trailer',
                    errorType: QCErrorType.IRRATIONAL_SIZE,
                    severity: 'warning',
                    reason: 'Kích thước trailer dài 16.5m vượt ngưỡng cho phép 12.0m',
                    metrics: {
                        dimensions: { length: 16.5, width: 2.8, height: 3.5 },
                        expectedDimensionsRange: 'Dài tối đa: 13.0m',
                    },
                    cvatUrl: '/tasks/42/jobs/103?frame=15&focus=trk_trailer_032',
                    status: 'pending',
                },
            ],
        },
        {
            id: 'scene_004',
            token: 'e2a77a445d47458197c36a4b3d7b4ef2',
            sceneName: 'scene-0757 (Singapore - Queenstown Express Merge)',
            location: 'Singapore - Ayer Rajah Expressway (AYE)',
            description: 'Đoạn đường cao tốc nhập làn tốc độ 75km/h, ánh sáng mặt trời đầy đủ',
            taskId: 42,
            jobId: 104,
            frameCount: 40,
            totalCuboids: 190,
            errorCounts: {
                [QCErrorType.FEW_LIDAR_POINTS]: 2,
                [QCErrorType.IRRATIONAL_SIZE]: 1,
                [QCErrorType.OVERLAPPING_CUBOIDS]: 0,
                [QCErrorType.OPPOSITE_HEADING]: 3,
                total: 6,
            },
            riskLevel: 'medium',
            suspectedCuboids: [
                {
                    id: 'cub_757_01',
                    trackId: 'trk_car_220',
                    frame: 18,
                    timestamp: '00:09.000',
                    label: 'car',
                    errorType: QCErrorType.OPPOSITE_HEADING,
                    severity: 'critical',
                    reason: 'Góc yaw lệch 171° so với trajectory di chuyển tốc độ 68km/h trên cao tốc',
                    metrics: {
                        yawAngleDeg: 12.0,
                        motionVectorDeg: 183.0,
                        angleDeltaDeg: 171.0,
                    },
                    cvatUrl: '/tasks/42/jobs/104?frame=18&focus=trk_car_220',
                    status: 'pending',
                },
                {
                    id: 'cub_757_02',
                    trackId: 'trk_car_228',
                    frame: 24,
                    timestamp: '00:12.000',
                    label: 'car',
                    errorType: QCErrorType.FEW_LIDAR_POINTS,
                    severity: 'warning',
                    reason: 'Chỉ có 4 điểm LiDAR do xe chạy ở khoảng cách xa >60m',
                    metrics: {
                        pointCount: 4,
                        minPointThreshold: 5,
                    },
                    cvatUrl: '/tasks/42/jobs/104?frame=24&focus=trk_car_228',
                    status: 'pending',
                },
            ],
        },
        {
            id: 'scene_005',
            token: '984534925b6845318395726207038166',
            sceneName: 'scene-0916 (Boston Cambridge - MIT Main St)',
            location: 'Cambridge - Main St & Ames St',
            description: 'Đoạn đường có nhiều người đi xe đạp và xe tay ga điện trên làn đường riêng',
            taskId: 42,
            jobId: 105,
            frameCount: 40,
            totalCuboids: 235,
            errorCounts: {
                [QCErrorType.FEW_LIDAR_POINTS]: 1,
                [QCErrorType.IRRATIONAL_SIZE]: 2,
                [QCErrorType.OVERLAPPING_CUBOIDS]: 2,
                [QCErrorType.OPPOSITE_HEADING]: 0,
                total: 5,
            },
            riskLevel: 'low',
            suspectedCuboids: [
                {
                    id: 'cub_916_01',
                    trackId: 'trk_bicycle_081',
                    frame: 10,
                    timestamp: '00:05.000',
                    label: 'bicycle',
                    errorType: QCErrorType.OVERLAPPING_CUBOIDS,
                    severity: 'warning',
                    reason: 'Cuboid xe đạp lồng vào bounding box người điều khiển (IoU 0.22)',
                    metrics: {
                        overlapIou: 0.22,
                        conflictingTrackId: 'trk_pedestrian_082',
                    },
                    cvatUrl: '/tasks/42/jobs/105?frame=10&focus=trk_bicycle_081',
                    status: 'pending',
                },
                {
                    id: 'cub_916_02',
                    trackId: 'trk_truck_102',
                    frame: 33,
                    timestamp: '00:16.500',
                    label: 'truck',
                    errorType: QCErrorType.IRRATIONAL_SIZE,
                    severity: 'warning',
                    reason: 'Chiều rộng cuboid 4.2m vượt quá bề rộng tối đa của làn đường đô thị',
                    metrics: {
                        dimensions: { length: 8.5, width: 4.2, height: 3.2 },
                        expectedDimensionsRange: 'Rộng chuẩn: 2.3-2.9m',
                    },
                    cvatUrl: '/tasks/42/jobs/105?frame=33&focus=trk_truck_102',
                    status: 'pending',
                },
            ],
        },
        {
            id: 'scene_006',
            token: '5a289945037d4038a8e137f867498c4b',
            sceneName: 'scene-1077 (Singapore - Jurong Port Bypass)',
            location: 'Singapore - Jalan Buroh',
            description: 'Tuyến đường cảng công nghiệp thông thoáng, các nhãn gán 3D chuẩn xác',
            taskId: 42,
            jobId: 106,
            frameCount: 40,
            totalCuboids: 180,
            errorCounts: {
                [QCErrorType.FEW_LIDAR_POINTS]: 0,
                [QCErrorType.IRRATIONAL_SIZE]: 0,
                [QCErrorType.OVERLAPPING_CUBOIDS]: 0,
                [QCErrorType.OPPOSITE_HEADING]: 0,
                total: 0,
            },
            riskLevel: 'clean',
            suspectedCuboids: [],
        },
    ],
};
